apiVersion: batch/v1
kind: CronJob
metadata:
  name: dodns-updater
spec:
  schedule: 0/5 * * * ?
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          restartPolicy: OnFailure
          containers:
          - name: do-dns-updater
            image: lwolf/dodns:latest
            env:
            - name: DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: dodns-configmap
                  key: domain
            - name: RECORD
              valueFrom:
                configMapKeyRef:
                  name: dodns-configmap
                  key: record
            - name: APIKEY
              valueFrom:
                configMapKeyRef:
                  name: dodns-configmap
                  key: apikey
          volumes:
          - name: config
            configMap:
              name: dodns-configmap
